### ISSUE TITLE
Add data visualization color globals for import

### ISSUE THREAD

**Issue by nvkelso** [tangrams/refill#61]
See https://github.com/tangrams/tangram/issues/418.

From @burritojustice's original description (which would need a different syntax in practice): 

add colorbrewer schemes to `color:`

```
layers:
    counties:
        polygon:
            color: OrRd[2]    
```

https://github.com/axismaps/colorbrewer/

hex is here, for reference:

https://github.com/google/palette.js/blob/master/palette.js#L931
