### ISSUE TITLE
Is mix: null okay?

### ISSUE THREAD

**Issue by nvkelso** [tangrams/refill#74]
Here we add a `mix: colorized_icons`, and then later we allow import of `mix: ` in other Mapzen basemap styles to unset that. This works, but it's not clear if it's a bug. Discuss!

Refill:

https://github.com/tangrams/refill-style/blob/1ed9bfd71151aaec2b1290d9b2450928a62bfb3b/themes/refill-icons.yaml#L6

Tron:

https://github.com/tangrams/tron-style/blob/828f0d3b1444daff61da19b440d2074d9d310d8c/themes/tron-icons.yaml#L4-L6

Import with Tron icons (full color):

```
import:
    - https://mapzen.com/carto/refill-style/9/refill-style.zip
    - https://mapzen.com/carto/refill-style/9/themes/color-purple-green.zip
    - https://mapzen.com/carto/refill-style/9/themes/label-10.zip
    - https://mapzen.com/carto/tron-style/5/themes/tron-icons.zip
```

Import with Tron icons (as colorized ala Refill), by moving the import order:

```
import:
    - https://mapzen.com/carto/refill-style/9/refill-style.zip
    - https://mapzen.com/carto/refill-style/9/themes/label-10.zip
    - https://mapzen.com/carto/tron-style/5/themes/tron-icons.zip
    - https://mapzen.com/carto/refill-style/9/themes/color-purple-green.zip
```

**Comment by tallytalwar** [comment]
What I know from writing the ES code, this is not a bug and is exactly how the property merging behaves on an import. Also having an empty value (null value) is a valid yaml.

The question though remains is how to communicate the use of an empty style property in the base icon styles. Also explain/communicate how ordering of imports affect the usage of this empty style property (`mix` in our case here)?

**Comment by bcamper** [comment]
Can you guys link to the scene YAML in question, for context?

**Comment by nvkelso** [comment]
Yes, see: https://github.com/tangrams/refill-style/issues/74#issue-260377706

**Comment by bcamper** [comment]
So yes, this works as far as currently implemented merging behavior is intended, however I'm concerned that it's a pretty brittle pattern (past experience suggests it likely breaks in future releases of the styles). In particular:

- Flipping a "flag" (colorized icons on/off) based solely on *import order* is not intuitive and prone to error.
- All the other styles that use the Mapzen icon library are now *coupled* to a Refill-specific implementation detail, because they must have a `mix:` to unset the icon library. (Besides the coupling, it's also rather obscure, even with the comment.)

In an ideal solution, turning icon colorization on/off would be **decoupled** both from import order and between styles -- something like a `global.mapzen_icon_library_colorize` flag that could default `false` and the Refill style could enable, with other users enabling/disabling as desired.

I haven't been able to spend enough time to try rewriting this in that way, but I wonder if something could be done with `globals` that either redefine the `mapzen_icon_library` (so that rather than merging, they are kept as two separate definitions that are simply "switched between") or `colorized-icons` style entirely (perhaps with an empty style defined as `{}`?).

@matteblair I'd like your thoughts here on the general issue and speculation of other solutions.

**Comment by tallytalwar** [comment]
Another proposed solution is to expose a global to control the mixing style on `mapzen-icon-library`. It would have been a bit more simpler using a boolean global, had we supported JS functions on `mix`. I do not think these are supported though.

Example:

1. Specify the [mix style](https://github.com/tangrams/refill-style/blob/14feb6bc26399d0e1dab5c24f6daea858daa1c32/themes/color-purple-green.yaml#L220) using a [global](https://github.com/tangrams/refill-style/blob/14feb6bc26399d0e1dab5c24f6daea858daa1c32/themes/color-purple-green.yaml#L29) in the refill color themes.

2. control the mixing of color by specifying a global in the final scene:

```yaml
# when following is defined, it overrides the mix style on the imported color theme, otherwise the icons gets the colored theme from the imported refill theme.
global:
    sdk-icon-color-style:

import:
    - https://mapzen.com/carto/refill-style/9/refill-style.zip
    - https://raw.githubusercontent.com/tangrams/refill-style/varun/test-colorized-global/themes/color-purple-green.yaml
    - https://mapzen.com/carto/refill-style/9/themes/label-10.zip
    - https://raw.githubusercontent.com/tangrams/tron-style/varun/test-colorized-global/themes/tron-icons.yaml
```

Here order of import won't determine the coloring or non-coloring of the base style icons. But the behavior will be explicitly defined by the use of the global.
